/* Phone and DOB are deliberately left blank here (this file is public); they live in data/CH details.xlsx.
   Power of 2 roster — one entry per CG (a pair of 2). CG38–CG41 were unnumbered on the list: numbers are provisional. */
window.CGS = [
  { cg:'CG1', governor:"Mummy Kiki", members:[ { name:"Nina", ch:"CH1", phone:'', dob:'', location:'', photo:'' }, { name:"Gifty", ch:"CH2", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG2', governor:"Mummy Kiki", members:[ { name:"Lucia", ch:"CH3", phone:'', dob:'', location:'', photo:'' }, { name:"Zifah", ch:"CH4", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG3', governor:"Mummy Kiki", members:[ { name:"Tifah", ch:"CH5", phone:'', dob:'', location:'', photo:'' }, { name:"Mary", ch:"CH6", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG4', governor:"Mummy Kiki", members:[ { name:"Kezia", ch:"CH7", phone:'', dob:'', location:'', photo:'' }, { name:"Cindy", ch:"CH8", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG5', governor:"Mummy Kiki", members:[ { name:"Mondie", ch:"CH9", phone:'', dob:'', location:'', photo:'' }, { name:"Jesse", ch:"CH10", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG6', governor:"Ninette", members:[ { name:"Juanita Adom-Barnor", ch:"CH11", phone:'', dob:'', location:'', photo:'' }, { name:"Angel Nanette Ghansah", ch:"CH12", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG7', governor:"Ninette", members:[ { name:"Chara Anyi", ch:"CH13", phone:'', dob:'', location:'', photo:'' }, { name:"Joan Adom-Barnor", ch:"CH14", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG8', governor:"Ninette", members:[ { name:"Elvin Odai", ch:"CH15", phone:'', dob:'', location:'', photo:'' }, { name:"Kofi Annan", ch:"CH16", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG9', governor:"Ninette", members:[ { name:"Benedicta Asomani", ch:"CH17", phone:'', dob:'', location:'', photo:'' }, { name:"Ninette Dodoo", ch:"CH18", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG10', governor:"Christiana Dzekoe", members:[ { name:"Grace Fianu", ch:"CH19", phone:'', dob:'', location:'', photo:'' }, { name:"Stephen Kudakpo", ch:"CH20", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG11', governor:"Christiana Dzekoe", members:[ { name:"Bernice Blewudzi", ch:"CH21", phone:'', dob:'', location:'', photo:'' }, { name:"Priscilla", ch:"CH22", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG12', governor:"Christiana Dzekoe", members:[ { name:"Christiana", ch:"CH23", phone:'', dob:'', location:'', photo:'' }, { name:"Cindy", ch:"CH24", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG13', governor:"Christiana Dzekoe", members:[ { name:"Godwin", ch:"CH25", phone:'', dob:'', location:'', photo:'' }, { name:"Princess", ch:"CH26", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG14', governor:"Helen Group", members:[ { name:"Helen", ch:"CH27", phone:'', dob:'', location:'', photo:'' }, { name:"Josephine", ch:"CH28", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG15', governor:"Helen Group", members:[ { name:"Sandra", ch:"CH29", phone:'', dob:'', location:'', photo:'' }, { name:"Morgan", ch:"CH30", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG16', governor:"Helen Group", members:[ { name:"Bernice", ch:"CH31", phone:'', dob:'', location:'', photo:'' }, { name:"Derry", ch:"CH32", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG17', governor:"Claudia", members:[ { name:"Elizabeth", ch:"CH33", phone:'', dob:'', location:'', photo:'' }, { name:"Pascaline", ch:"CH34", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG18', governor:"Dorcas L", members:[ { name:"David", ch:"CH35", phone:'', dob:'', location:'', photo:'' }, { name:"Daniella", ch:"CH36", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG19', governor:"Dorcas L", members:[ { name:"Dorcas", ch:"CH37", phone:'', dob:'', location:'', photo:'' }, { name:"Rebecca", ch:"CH38", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG20', governor:"Dorcas L", members:[ { name:"Jonathan", ch:"CH39", phone:'', dob:'', location:'', photo:'' }, { name:"Rebecca", ch:"CH40", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG21', governor:"Johanna", members:[ { name:"Tina Andaful", ch:"CH41", phone:'', dob:'', location:'', photo:'' }, { name:"Famous Klutse", ch:"CH42", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG22', governor:"Johanna", members:[ { name:"Nana Yaa", ch:"CH43", phone:'', dob:'', location:'', photo:'' }, { name:"Lp Johanna", ch:"CH44", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG23', governor:"Lois", members:[ { name:"Raphael Kumah", ch:"CH45", phone:'', dob:'', location:'', photo:'' }, { name:"David Odoom", ch:"CH46", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG24', governor:"Lois", members:[ { name:"Vonzell Asante", ch:"CH47", phone:'', dob:'', location:'', photo:'' }, { name:"Michelle Erskine", ch:"CH48", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG25', governor:"Lois", members:[ { name:"Isabella Kabukuor Atrikpe", ch:"CH49", phone:'', dob:'', location:'', photo:'' }, { name:"Doreen Akapko", ch:"CH50", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG26', governor:"Lois", members:[ { name:"Lois Nterful", ch:"CH51", phone:'', dob:'', location:'', photo:'' }, { name:"Patience Nortey", ch:"CH52", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG27', governor:"Joanita", members:[ { name:"Portia Danquah", ch:"CH53", phone:'', dob:'', location:'', photo:'' }, { name:"Patricia Nunekpeku", ch:"CH54", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG28', governor:"Joanita", members:[ { name:"Papa Yaw Ashun", ch:"CH55", phone:'', dob:'', location:'', photo:'' }, { name:"Betty", ch:"CH56", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG29', governor:"Anne", members:[ { name:"Anne Wuni", ch:"CH57", phone:'', dob:'', location:'', photo:'' }, { name:"Leticia Ewudzi", ch:"CH58", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG30', governor:"Anne", members:[ { name:"Cynthia Tetteh", ch:"CH59", phone:'', dob:'', location:'', photo:'' }, { name:"Esther Donkor", ch:"CH60", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG31', governor:"Lucia", members:[ { name:"Eyram Edah", ch:"CH61", phone:'', dob:'', location:'', photo:'' }, { name:"Wilhermina Narh", ch:"CH62", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG32', governor:"Lucia", members:[ { name:"Abigail Domerpkor", ch:"CH63", phone:'', dob:'', location:'', photo:'' }, { name:"", ch:"", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG33', governor:"Hannah-Joy", members:[ { name:"Amina", ch:"CH64", phone:'', dob:'', location:'', photo:'' }, { name:"HJ", ch:"CH65", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG34', governor:"Hannah-Joy", members:[ { name:"Johnny", ch:"CH66", phone:'', dob:'', location:'', photo:'' }, { name:"Michael", ch:"CH67", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG35', governor:"Hannah-Joy", members:[ { name:"Sarah", ch:"CH68", phone:'', dob:'', location:'', photo:'' }, { name:"Johnny", ch:"CH69", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG36', governor:"Hannah-Joy", members:[ { name:"Daniel", ch:"CH70", phone:'', dob:'', location:'', photo:'' }, { name:"Elvis", ch:"CH71", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG37', governor:"Hannah-Joy", members:[ { name:"Oheema", ch:"CH72", phone:'', dob:'', location:'', photo:'' }, { name:"Adom", ch:"CH73", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG38', governor:"Aseda", members:[ { name:"Honesty", ch:"CH74", phone:'', dob:'', location:'', photo:'' }, { name:"Joana Shiela", ch:"CH75", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG39', governor:"Michelle", members:[ { name:"Michelle", ch:"CH76", phone:'', dob:'', location:'', photo:'' }, { name:"", ch:"", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG40', governor:"Celine", members:[ { name:"Celine", ch:"CH77", phone:'', dob:'', location:'', photo:'' }, { name:"", ch:"", phone:'', dob:'', location:'', photo:'' } ] },
  { cg:'CG41', governor:"Janet Thomas", members:[ { name:"Janet", ch:"CH78", phone:'', dob:'', location:'', photo:'' }, { name:"", ch:"", phone:'', dob:'', location:'', photo:'' } ] },
];
